version: '3.8'

services:
  cart-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5436:5432"

    volumes:
      - cart_db_data:/var/lib/postgresql/data

  cart-service:
    build: .
    ports:
      - "8004:8000"
    depends_on:
      - cart-db
    env_file:
      - .env

volumes:
  cart_db_data:

networks:
  default:
    external:
      name: microservices-net
